Traceback (most recent call last):
  File "<ipython-input-6-7986ac11b3ee>", line 4, in <module>
    raise Exception('エラーメッセージ')
Exception: エラーメッセージ
